# .releaserc.yaml
plugins:
  - - "@semantic-release/commit-analyzer"
    - preset: "conventionalcommits"
  - - "@semantic-release/release-notes-generator"
    - preset: "conventionalcommits"
  - - "@semantic-release/npm"
  - - "@semantic-release/github"
    - successCommentCondition: false

branches:
  - main
  - name: rc/*
    prerelease: '${name.replace(/^rc\//, "rc-")}'
